#!/bin/bash

usage() { echo "Usage: $0 --name <fluentd> --link <elasticsearch> --port <8888>" 1>&2; exit 1; }

UNKNOWN_ARGS=""
NAME=fluentd
LINK=elasticsearch
PORT=8888
while [ "$1" != "" ] ; do
    case "$1" in
       --name) NAME="$2" ; shift 2 ;;
       --link) LINK="$2" ; shift 2 ;;
       --port) PORT="$2" ; shift 2 ;;
       *) UNKNOWN_ARGS="$UNKNOWN_ARGS $1" ; shift ;;
    esac
done

if [ "$UNKNOWN_ARGS" != "" ] ; then
	usage
	echo "UNKNOWN ARGUMENT: $UNKNOWN_ARGS"
else 
	echo docker run -d -name "${NAME}" -p :${PORT}:8888 -link ${LINK}:es hbouvier/fluentd
	docker run -d -name "${NAME}" -p :${PORT}:8888 -link ${LINK}:es hbouvier/fluentd
fi
